mad_experience_homepage:
    pattern:  /mi-espacio
    defaults: { _controller: MADExperienceBundle:GatheringPlace:home }

mad_experience_my_experiences:
    pattern:  /mis-experiencias
    defaults: { _controller: MADExperienceBundle:GatheringPlace:myExperiences }