parameters:
#    mad_experience.example.class: MAD\ExperienceBundle\Example

services:
#    mad_experience.example:
#        class: %mad_experience.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
