security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_TEACHER, ROLE_RESEARCHER, ROLE_ARTIST, ROLE_ARTIST_TEACHER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                success_handler: mad_user.authentication.handler.first_pwd_change_handler
                default_target_path: /mi-espacio
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
#        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/investigacion, role: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_ADMIN, ROLE_TEACHER, ROLE_RESEARCHER, ROLE_ARTIST, ROLE_ARTIST_TEACHER] }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mi-espacio, role: [ROLE_ADMIN, ROLE_TEACHER, ROLE_RESEARCHER, ROLE_ARTIST, ROLE_ARTIST_TEACHER] }
        - { path: ^/profile, role: [ROLE_ADMIN, ROLE_TEACHER, ROLE_RESEARCHER, ROLE_ARTIST, ROLE_ARTIST_TEACHER] }
        - { path: ^/mis-experiencias, role: [ROLE_ADMIN,ROLE_TEACHER, ROLE_RESEARCHER, ROLE_ARTIST, ROLE_ARTIST_TEACHER] }
        - { path: ^/experiencias-compartidas, role: [ROLE_ADMIN, ROLE_TEACHER, ROLE_RESEARCHER, ROLE_ARTIST, ROLE_ARTIST_TEACHER] }
        - { path: ^/experiencias-compartidas, role: [ROLE_ADMIN, ROLE_TEACHER, ROLE_RESEARCHER, ROLE_ARTIST, ROLE_ARTIST_TEACHER] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
