parameters:
    mad_comment.send_email_listener.class: MAD\CommentBundle\EventListener\SendEmailListener

services:
    mad_comment.send_email_listener:
        class: %mad_comment.send_email_listener.class%
        arguments: [@mailer, @templating]
        tags:
            - { name: kernel.event_subscriber }
