MAD\UserBundle\Entity\Group:
    type: entity
    table: groups
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
