MAD\UserBundle\Entity\User:
    type:  entity
    table: users
    repositoryClass: MAD\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        experiences:
            targetEntity: MAD\ExperienceBundle\Entity\Experience
            mappedBy: user
            cascade: ["all"]