parameters:
#    mad_user.example.class: MAD\UserBundle\Example

services:
#    mad_user.example:
#        class: %mad_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
