parameters:
    mad_user.authentication.handler.first_pwd_change_handler.class: MAD\UserBundle\Security\Authentication\Handler\FirstPasswordChangeHandler

services:
    mad_user.authentication.handler.first_pwd_change_handler:
        class:  %mad_user.authentication.handler.first_pwd_change_handler.class%
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }